#  Chapter1

 [PyTorch论坛](https://discuss.pytorch.org)

## 什么是pytorch
Pytorch是基于python的科学计算包，为两类受众提供服务
* 作为Numpy的替换，让你可以使用GPU的算力
* 作为一个深度学习计算平台提供最大的计算灵活性与速度

## Tensor
tensor与Numpy的高维数据概念类似，但tensor可以在GPU上进行计算

In [49]:
# 导入
import torch

构造一个未初始化的5x3的张量

In [50]:
x = torch.empty(5,3)
x

tensor([[ 0.0000e+00, -0.0000e+00,  1.2157e+01],
        [-2.0005e+00,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

构造一个随机初始化的张量

In [80]:
x = torch.rand(5,3)
x

tensor([[0.7589, 0.0812, 0.6899],
        [0.7126, 0.3862, 0.6166],
        [0.9029, 0.1078, 0.6491],
        [0.1822, 0.7650, 0.3820],
        [0.3732, 0.1730, 0.9379]])

构建一个全部为0

In [81]:
x = torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

数据类型

In [82]:
x.dtype

torch.float32

In [83]:
# 改变格式的两种方法
y = x.long()
z = torch.zeros(5,3,dtype=torch.long)
print(y)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


构造一个tensor

In [84]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

从已有的tensor中构建一个tensor，该tensor将于原来的tensor具有相同的数据类型

In [96]:
x = y.new_ones(5,3)
print(x)
y = x.new_ones(5,3,dtype=torch.double)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


随机产生一个于x相同形状的tensor

In [97]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[-0.7920,  0.5455,  0.0620],
        [ 1.2256, -0.7768, -0.2202],
        [-0.0794, -0.5387,  0.8548],
        [ 0.7359, -0.0879, -1.9654],
        [ 0.1079,  0.6515, -1.1404]])

获取tensor形成

In [98]:
x.shape

torch.Size([5, 3])

In [99]:
x.size()

torch.Size([5, 3])

## Tensor 运算

In [100]:
y = torch.rand(5,3)
y

tensor([[0.2924, 0.5766, 0.6750],
        [0.2935, 0.6938, 0.7387],
        [0.8530, 0.9555, 0.3102],
        [0.6852, 0.5002, 0.6912],
        [0.7507, 0.4053, 0.5735]])

加法

In [101]:
x+y

tensor([[-0.4995,  1.1221,  0.7370],
        [ 1.5191, -0.0830,  0.5184],
        [ 0.7735,  0.4168,  1.1651],
        [ 1.4211,  0.4123, -1.2742],
        [ 0.8586,  1.0568, -0.5669]])

In [102]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
# result = x+y
result

tensor([[-0.4995,  1.1221,  0.7370],
        [ 1.5191, -0.0830,  0.5184],
        [ 0.7735,  0.4168,  1.1651],
        [ 1.4211,  0.4123, -1.2742],
        [ 0.8586,  1.0568, -0.5669]])

> in-place运行，加下划线‘_’的方法会改变其成员的原有值

In [103]:
y.add_(x)

tensor([[-0.4995,  1.1221,  0.7370],
        [ 1.5191, -0.0830,  0.5184],
        [ 0.7735,  0.4168,  1.1651],
        [ 1.4211,  0.4123, -1.2742],
        [ 0.8586,  1.0568, -0.5669]])

In [104]:
y

tensor([[-0.4995,  1.1221,  0.7370],
        [ 1.5191, -0.0830,  0.5184],
        [ 0.7735,  0.4168,  1.1651],
        [ 1.4211,  0.4123, -1.2742],
        [ 0.8586,  1.0568, -0.5669]])

indexing索引，类似Numpy

In [110]:
x[1:,2:]
# 阐述类似列表索引
# [ ]内两个参数索引范围，第一个代表行索引范围，第二代表列参数索引范围
# 类似[1:, 2:]
# 代表取tensor x的第二行到最后一行，第三列到最后一列的内容
# 索引从 0 开始

tensor([[-0.2202],
        [ 0.8548],
        [-1.9654],
        [-1.1404]])

Resizing，改变tensor的维度

In [115]:
x = torch.randn(4,4) #
# x.view(16)
# x.view(2,8)
x.view(2,-1) # -1 代表自动适配
# 不可以同时传入两个-1，已不能输入一个无法整除的参数

tensor([[ 2.6282, -0.4764,  0.8818, -1.2674,  0.3267, -1.4255,  1.2062,  0.2760],
        [-1.0746, -1.3563,  1.0906, -1.6647,  0.1716,  0.1973,  1.0783, -0.2211]])